<?php

namespace Database\Seeders;

use App\Models\PlantType;
use Illuminate\Database\Seeder;

class PlantTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plantTypes = [
            ['name' => 'Beetroot', 'latin' => 'Beta vulgaris', 'family_id' => 2, 'perennial' => false,
                'dates_best_sow' => 'Mar, Jun', 'dates_main_harvest' => 'Mar, Jun',
                'feeder_type' => 'Light', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => 'Mushroom compost, Boron', 'fertiliser' => 'Mushroom compost, Boron', 'when_to_fertilise' => 'Previous crop, Foliar feed',
                'multisow' => 3, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Fairly strong', 'competition_period' => 'Keep competition free for 4 weeks from planting early in the season, less so in spring',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => 'Onion, Salad',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'beets.jpg', 'plant_type_img' => 'planttype/beetroot.100x100.png', ],
            ['name' => 'Broad Bean', 'latin' => 'Vicia faba', 'family_id' => 9, 'perennial' => false,
                'dates_best_sow' => 'Oct, Nov', 'dates_main_harvest' => 'Jun, Jul',
                'feeder_type' => 'Light', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Once established beans compete well with interplants, provided they have enough water, give them 4 weeks without competition after breaking surface',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'favabeans.jpg', 'plant_type_img' => 'planttype/broadbean.100x100.png', ],
            ['name' => 'Broccoli', 'latin' => 'Brassica oleracea var. Italica', 'family_id' => 3, 'perennial' => false,
                'dates_best_sow' => 'Jul', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Poultry manure, Mushroom compost', 'fertiliser' => 'Poultry manure, Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Avoid competition for 3 weeks after transplanting in late spring onwards, but 4 weeks when planted in late winter and early spring',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => 'Beetroot, Lettuce, Onion, Salad', 'relay_plant_with' => '', 'germ_temp_img' => 'minibroccoli.jpg', 'plant_type_img' => 'planttype/broccolipurple-sprouting.100x100.png', ],
            ['name' => 'Cabbage', 'latin' => 'Brassica oleracea capitata', 'family_id' => 3, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Avoid competition for 3 weeks after transplanting in late spring onwards, but 4 weeks in late winter and early spring',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'cabbage.jpg', 'plant_type_img' => 'planttype/spring-cabbage.100x100.png', ],
            ['name' => 'Calabrese', 'latin' => 'Brassica oleracea', 'family_id' => 3, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Avoid competition for 3 weeks after transplanting in late spring onwards, but 4 weeks in late winter and early spring',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'broccoli.jpg', 'plant_type_img' => 'planttype/calabrese.100x100.png', ],
            ['name' => 'Carrot', 'latin' => 'Daucus carota subsp. sativus', 'family_id' => 4, 'Perennial' => false,
                'dates_best_sow' => 'Nov, Apr, May, Jun', 'dates_main_harvest' => 'Mar, May, Jul',
                'feeder_type' => 'Light', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => 'Multi-purpse compost, Seaweed meal', 'fertiliser' => 'Multi-purpse compost, Seaweed meal', 'when_to_fertilise' => 'Previous crop',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Weak', 'competition_period' => 'Avoid any competition until roots are mature',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => 'Lettuce', 'germ_temp_img' => 'carrots.jpg', 'plant_type_img' => 'planttype/carrot.100x100.png', ],
            ['name' => 'Cauliflower', 'latin' => 'Brassica oleracea var. botrytis', 'family_id' => 3, 'perennial' => false, 'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => "Strong competitor once established, for 3-4 weeks after transplanting, by then it's growing too fast to interplant with anything but radish. ",
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'cauliflower.jpg', 'plant_type_img' => 'planttype/cauliflower.100x100.png', ],
            ['name' => 'Cucumber', 'latin' => 'Cucumis sativus', 'family_id' => 5, 'perennial' => false,
                'dates_best_sow' => 'Apr', 'dates_main_harvest' => 'Apr',
                'feeder_type' => 'Medium', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Warm loving (10c or above best)',
                'competitor' => 'Fairly strong', 'competition_period' => 'Avoid competition for 4 weeks after transplanting, after that they are fairly strong',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => 'Lettuce', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'cucumbers.jpg', 'plant_type_img' => 'planttype/cucumber.100x100.png', ],
            ['name' => 'Field beans', 'latin' => 'Vicia faba', 'family_id' => 9, 'perennial' => false,
                'dates_best_sow' => 'Sep, Oct', 'dates_main_harvest' => 'Nov, Dec, Jan, Mar, Apr',
                'feeder_type' => 'Nitrogen fixer', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Once established beans compete well with interplants, provided they have enough water, give them 4 weeks without competition after breaking surface',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => 'Green Garlic, Onion, Salad', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'favabeans.jpg', 'plant_type_img' => 'planttype/broadbean.100x100.png', ],
            ['name' => 'Garlic', 'latin' => 'Allium sativum', 'family_id' => 1, 'perennial' => false,
                'dates_best_sow' => 'Oct, Nov, Feb, Mar', 'dates_main_harvest' => 'Jun, Jul',
                'feeder_type' => '', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Weak', 'competition_period' => "Not a strong competitor,  for the first 6-8 weeks after it's started to grow strongly in spring",
                'companions' => '', 'interplant_into' => 'Corn Salad, Lettuce, Spinach (True)', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => '', 'plant_type_img' => 'planttype/garlic.100x100.png', ],
            ['name' => 'Leek', 'latin' => 'Allium porrum', 'family_id' => 1, 'perennial' => false,
                'dates_best_sow' => 'Feb, Mar', 'dates_main_harvest' => 'Aug, Sep, Oct, Nov, Dec, Jan, Feb, Mar',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => 1, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Medium', 'competition_period' => "Avoid competition for 4 weeks after transplanting, but once established it's deep rooted so paired with shallow or quick growing crops is ok",
                'companions' => '', 'interplant_into' => 'Kalettes, Kale, Celery, Indoor (cordon) tomato, Outdoor (cordon) tomato', 'interplant_with' => '', 'relay_plant_into' => 'Spinach (True), Lettuce', 'relay_plant_with' => '', 'germ_temp_img' => 'leeks.jpg', 'plant_type_img' => 'planttype/leek.100x100.png', ],
            [
                'name' => 'Pea', 'latin' => 'Lathyrus oleraceus', 'family_id' => 9, 'perennial' => false,
                'dates_best_sow' => 'Mar, Apr, May', 'dates_main_harvest' => 'Jun, Jul',
                'feeder_type' => 'Light', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Medium', 'competition_period' => 'Avoid competition for 40 days after planting, or until they are 8 leaf nodes high.  After which they are reasonable competitors provided they get enough water!',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'peas.jpg', 'plant_type_img' => 'planttype/peas.100x100.png',
            ],
            [
                'name' => 'Spinach', 'latin' => 'Spinacia oleracea', 'family_id' => 2, 'perennial' => false,
                'dates_best_sow' => 'Feb, Apr, Aug, Sep', 'dates_main_harvest' => 'Feb, Mar, Apr, May, Jun, Sep, Oct, Nov',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => 'Before planting',
                'multisow' => null, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Medium', 'competition_period' => 'Spinach is a weak competitor in Autumn, but a medium one in spring.  It works really well when relay planted with over wintered flowering brassicas for cabbages',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => 'Onion, Salad',
                'relay_plant_into' => '', 'relay_plant_with' => 'Calabrese, Cabbage, Cauliflower', 'germ_temp_img' => 'spinach.jpg', 'plant_type_img' => 'planttype/spinach.100x100.png',
            ],
            [
                'name' => 'Swede', 'latin' => 'Brassica napus', 'family_id' => 3, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => '', 'root_depth' => '',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => '',
                'competitor' => '', 'competition_period' => '',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'rutabaga.jpg', 'plant_type_img' => 'planttype/swede.100x100.png',
            ],
            [
                'name' => 'Tomato', 'latin' => 'Lycopersicon esculentum', 'family_id' => 10, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Deep Rooting 24″-36″+ (60-90 cm+)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Not very cold tolerant (well above freezing)',
                'competitor' => 'Strong', 'competition_period' => 'Tomatoes are strong competitors, once established, give them about 3 weeks and ensure they are not shaded.  Once established most interplants will be removed due to shading',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'tomatoes.jpg', 'plant_type_img' => 'planttype/tomato.100x100.png',

            ],
            [
                'name' => 'Courgette', 'latin' => 'Cucurbita pepo', 'family_id' => 5, 'Perennial' => false,
                'dates_best_sow' => 'Apr, May', 'dates_main_harvest' => 'Apr, May',
                'feeder_type' => 'Heavy', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Cold tolerant (just above freezing ok)',
                'competitor' => 'Medium', 'competition_period' => "Squash don't like their roots being disturbed, so avoid interplanting close to them",
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => 'Spinach (True)', 'relay_plant_with' => '', 'germ_temp_img' => 'summersquash.jpg', 'plant_type_img' => 'planttype/courgette.100x100.png',
            ],
            [
                'name' => 'Chives ', 'latin' => 'Allium schoenoprasum', 'family_id' => 1, 'perennial' => true,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => '', 'root_depth' => '',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => '',
                'competitor' => '', 'competition_period' => '',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => '', 'plant_type_img' => 'planttype/chives.100x100.png',
            ],
            [
                'name' => 'Lettuce', 'latin' => 'Lactuca sativa', 'family_id' => 11, 'perennial' => false,
                'dates_best_sow' => 'Feb, Jun, Jul, Aug, Sep, Nov', 'dates_main_harvest' => 'Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec',
                'feeder_type' => 'Medium', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => 'Before planting',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Avoid competition for 4 weeks after transplanting, but after that it grows well with competition',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'lettuce.jpg', 'plant_type_img' => 'planttype/lettuce-hearting.100x100.png',
            ],
            [
                'name' => 'Radish', 'latin' => 'Raphanus raphanistrum', 'family_id' => 3, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Give them 2 weeks to get established after transplanting, or 3 weeks after emergence of sown direct.  Longer if planted in early spring',
                'companions' => '', 'interplant_into' => 'Lettuce, Kale, Spinach (True)', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'radishes.jpg', 'plant_type_img' => 'planttype/raddish.100x100.png',
            ],
            [
                'name' => 'Hot pepper', 'latin' => 'Capsicum annuum', 'family_id' => 10, 'perennial' => false,
                'dates_best_sow' => '', 'dates_main_harvest' => '',
                'feeder_type' => 'Heavy', 'root_depth' => 'Medium Rooting 18″-24″ (45-60 cm)',
                'mulch' => '', 'fertiliser' => '', 'when_to_fertilise' => '',
                'multisow' => null, 'hardiness_young_plants' => 'Warm loving (10c or above best)',
                'competitor' => 'Strong', 'competition_period' => 'Peppers compete well once established, but give them about 4 weeks to establish first',
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'peppers.jpg', 'plant_type_img' => 'planttype/chilli.100x100.png',
            ],
            [
                'name' => 'Brussels Sprouts', 'latin' => 'Brassica oleracea var. gemmifera', 'family_id' => 3, 'perennial' => false, 
                'dates_best_sow' => 'Mar', 'dates_main_harvest' => 'Nov, Dec, Jan, Feb', 
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)', 
                'mulch' => 'Mushroom compost, Green manure (field beans), Poultry manure, Cow manure', 'fertiliser' => 'Mushroom compost, Green manure (field beans), Poultry manure, Cow manure', 'when_to_fertilise' => '', 
                'multisow' => 1, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)', 
                'competitor' => 'Medium', 'competition_period' => "Avoid competition for 4 weeks while it gets established and then again in early autumn as it starts to loose it's leaves", 
                'companions' => '', 'interplant_into' => '', 'interplant_with' => 'Radish, Leek', 'relay_plant_into' => 'Spinach (True), Lettuce', 'relay_plant_with' => '',  'plant_type_img' => 'planttype/brusselssprout.100x100.png',
            ],
            [
                'name' => 'Onion, Bulbing', 'latin' => 'Allium Cepa', 'family_id' => 1, 'perennial' => false,
                'dates_best_sow' => 'Jan, Feb, Aug', 'dates_main_harvest' => 'Jun, Jul, Aug',
                'feeder_type' => 'Medium', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Well rotted horse manure', 'fertiliser' => 'Well rotted horse manure', 'when_to_fertilise' => 'Before planting',
                'multisow' => null, 'hardiness_young_plants' => 'Hardy (frequent frosts ok)',
                'competitor' => 'Weak', 'competition_period' => 'No competition once bulbing starts in mid April (overwintered) or mid May (main crop)',
                'companions' => '', 'interplant_into' => 'Parsnip', 'interplant_with' => '',
                'relay_plant_into' => 'Lettuce, Spinach (True)', 'relay_plant_with' => '', 'germ_temp_img' => 'onions.jpg', 'plant_type_img' => 'planttype/onion-brown.100x100.png',
            ],
            [
                'name' => 'Onion, Salad', 'latin' => 'Allium Cepa', 'family_id' => 1, 'perennial' => false,
                'dates_best_sow' => 'Feb, Mar, Apr, May, Jun, Jul, Aug, Sep', 'dates_main_harvest' => 'Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec',
                'feeder_type' => 'Medium', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)',
                'mulch' => 'Mushroom compost', 'fertiliser' => 'Mushroom compost', 'when_to_fertilise' => '',
                'multisow' => 1, 'hardiness_young_plants' => 'Just hardy (infrequent frosts ok)',
                'competitor' => 'Strong', 'competition_period' => 'Grows well with competition, which reduces tendency to bulb and stimulates green growth instead',
                'companions' => '', 'interplant_into' => 'Lettuce, Corn Salad, Spinach (True)', 'interplant_with' => '',
                'relay_plant_into' => '', 'relay_plant_with' => '', 'germ_temp_img' => 'onions.jpg', 'plant_type_img' => 'planttype/spring-onion.100x100.png',
            ],
            [
                'name' => 'Potato', 'latin' => 'Solanum tuberosum', 'family_id' => 10, 'perennial' => false, 
                'dates_best_sow' => '', 'dates_main_harvest' => '', 
                'feeder_type' => 'Heavy', 'root_depth' => 'Shallow Rooting 12″-18″ (30-45 cm)', 
                'mulch' => 'Well rotted horse manure', 'fertiliser' => 'Well rotted horse manure', 'when_to_fertilise' => '', 
                'multisow' => null, 'hardiness_young_plants' => 'Cold tolerant (just above freezing ok)', 
                'competitor' => 'Strong', 'competition_period' => 'Strong competitors once established, about 4 weeks after emergence, but hard to interplant', 
                'companions' => '', 'interplant_into' => '', 'interplant_with' => '', 'relay_plant_into' => '', 'relay_plant_with' => '',  'plant_type_img' => 'planttype/potato.100x100.png',
            ],

        ];

        foreach ($plantTypes as $key => $value) {
            PlantType::create($value);
        }

    }
}
