<?php

namespace Database\Seeders;

use App\Models\Succession;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SuccessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $successions = [
            ['succession_type_id' => 1, 
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Aqua Dulce', 
            'sow' => 'Mid Oct', 
            'plant' => 'Mid Oct', 
            'firstHarvest' => 'Early May', 
            'lastHarvest' => 'Early Jun'],
            ['succession_type_id' => 2,
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Aqua Dulce', 
            'sow' => 'Late Oct', 
            'plant' => 'Late Oct', 
            'firstHarvest' => 'Late May', 
            'lastHarvest' => 'Mid Jun'],
            ['succession_type_id' => 3,
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Aqua Dulce', 
            'sow' => 'Early Nov', 
            'plant' => 'Early Nov', 
            'firstHarvest' => 'Early Jun',
            'lastHarvest' => 'Late Jun'],
            ['succession_type_id' => 4,
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Aqua Dulce', 
            'sow' => 'Late Feb, Early Mar', 
            'plant' => 'Late Feb, Early Mar', 
            'firstHarvest' => 'Early Jul', 
            'lastHarvest' => 'Late Jul'],
            ['succession_type_id' => 7,
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Aqua Dulce', 
            'sow' => 'Early Apr', 
            'plant' => 'Early Apr', 
            'firstHarvest' => 'Mid Jul', 
            'lastHarvest' => 'Early Aug'],
            ['succession_type_id' => 8, 
            'plant_type_id' => 2,
            // 'plant_type' => 'Broad Bean',
            // 'variety' => 'Luz De Otono', 
            'sow' => 'Jul, Aug', 
            'plant' => 'Jul, Aug',
            'firstHarvest' => 'Oct, Nov', 
            'lastHarvest' => 'Late Nov'],
            
            ['succession_type_id' => 1, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => 'Pablo F1', 
            'sow' => 'Early Jan', 
            'plant' => 'Early Feb', 
            'firstHarvest' => 'Early May', 
            'lastHarvest' => 'Early Jul'],
            ['succession_type_id' => 2, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => 'Boltardy', 
            'sow' => 'Mid Feb',
            'plant' => 'Mid Mar',
            'firstHarvest' => 'Early Jun', 
            'lastHarvest' => 'Early Jul'],
            ['succession_type_id' => 3, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => 'Boltardy', 
            'sow' => 'Mid Mar',
            'plant' => 'Mid Apr',
            'firstHarvest' => '', 
            'lastHarvest' => ''],
            ['succession_type_id' => 4, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => '', 
            'sow' => 'Mid Apr', 
            'plant' => 'Mid May',
            'firstHarvest' => 'Early Aug', 
            'lastHarvest' => 'Late Sep'],
            ['succession_type_id' => 7, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => 'Boltardy', 
            'sow' => 'Mid May, Early Jun', 
            'plant' => 'Mid Jun Early Jul',
            'firstHarvest' => 'Early Oct', 
            'lastHarvest' => 'Early Nov'],
            ['succession_type_id' => 8, 
            'plant_type_id' => 1,
            // 'plant_type' => 'Beetroot',
            // 'variety' => 'Boltardy', 
            'sow' => 'Late Jun',
            'plant' => 'Late Jul',
            'firstHarvest' => 'Nov', 
            'lastHarvest' => 'Late Dec'],
        ];


        foreach( $successions as $key => $value ) {
            Succession::create($value);
        }    

    }
}
// ['name' => 'Super early', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
// ['name' => 'First early', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
// ['name' => 'Second early', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
// ['name' => 'Early main', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
// ['name' => 'Main crop', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
// ['name' => 'Late crop', 
// 'succession_type_id' => '', 
// 'variety' => '', 
// 'sow' => '', 
// 'plant' => '', 
// 'firstHarvest' => '', 
// 'lastHarvest' => ''],
